#!/usr/bin/env bash
# .crm/config.sh — CRM configuration for labelwatch
#
# Generated by init-client.sh (stack: nextjs)
# Customize as needed. All values have sensible defaults.

# Identity
CRM_PROJECT_NAME="labelwatch"
CRM_PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Repos to check for clean state (label:path pairs)
CRM_REPOS=("project:${CRM_PROJECT_ROOT}")

# Dependencies required on PATH
CRM_REQUIRED_DEPS="jq"

# Build commands (empty = skip gate)
CRM_LINT_CMD=""
CRM_TEST_CMD=""
CRM_BUILD_CMD=""
CRM_TYPECHECK_CMD=""

# Container images (name:dockerfile:context entries, empty = no images)
CRM_IMAGES=()

# VM config (0 = no VMs; entries: label:ssh_target:vmx_path:vmx_host)
CRM_VM_COUNT=0
CRM_VMS=()

# Optional integrations
CRM_BEADS_ENABLED=false
CRM_REQUIRE_TAILSCALE=false
CRM_REQUIRE_PLAN=1

# Smoke test command (empty = skip)
CRM_SMOKE_CMD=""

# Compose file to validate (empty = skip)
CRM_COMPOSE_FILE=""

# Governance (G050) — set CRM_GOVERNANCE_ENABLED=true to activate.
# When enabled, scans CRM_COMPOSE_FILE for forbidden auth patterns and
# (if CRM_DECLARED_SERVICES is non-empty) detects undeclared compose services.
# No-op when CRM_GOVERNANCE_ENABLED=false (default, backward compatible).
# CRM_GOVERNANCE_ENABLED=false
# CRM_FORBIDDEN_ENV_PATTERNS=()    # e.g. ("SECRET_KEY" "INTERNAL_API_URL")
# CRM_DECLARED_SERVICES=()         # e.g. ("web" "worker") — leave empty to skip check

# Visual inspection (G025) — screenshot diff against reference site
# Set all three to enable the built-in runner, or set CRM_VISUAL_CMD for custom.
# CRM_VISUAL_REFERENCE_URL=""     # Base URL of reference site
# CRM_VISUAL_PREVIEW_URL=""       # Base URL of preview/dev site
# CRM_VISUAL_PAGES=()             # Paths to compare: ("/" "/about" "/contact")
# CRM_VISUAL_VIEWPORT="1280,800"  # Viewport size W,H
# CRM_VISUAL_THRESHOLD="0.05"     # Max allowed diff ratio (0.0-1.0)
# CRM_VISUAL_FULL_PAGE="true"     # Capture full scrollable page
# CRM_VISUAL_WAIT_MS="3000"       # Wait ms after page load before capture
# CRM_VISUAL_CMD=""               # Custom command (overrides built-in runner)
